"""Report — a multi-section analytical document generated by the agent.

`content` holds the assembled sections: a list of
{title, narrative, charts: [vega_spec, ...]}.
"""
from __future__ import annotations

import enum
import uuid

from sqlalchemy import Boolean, Enum as SAEnum
from sqlalchemy import Float, ForeignKey, Integer, String, Text, Uuid
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin, UUIDMixin


class ReportStatus(str, enum.Enum):
    running = "running"
    completed = "completed"
    failed = "failed"


class CreditState(str, enum.Enum):
    """Where this report is in the reserve -> capture/release credit lifecycle."""

    none = "none"          # not yet charged (created, not generated)
    held = "held"          # credits reserved for an in-flight generation
    captured = "captured"  # credits spent (generation completed)
    released = "released"  # hold refunded (generation failed / cancelled)


class Report(UUIDMixin, TimestampMixin, Base):
    __tablename__ = "reports"

    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False
    )
    dataset_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("datasets.id", ondelete="CASCADE"), index=True, nullable=False
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    goal: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[ReportStatus] = mapped_column(
        SAEnum(ReportStatus, name="reportstatus"),
        default=ReportStatus.running,
        nullable=False,
    )
    content: Mapped[list | None] = mapped_column(JSONB, nullable=True)
    error: Mapped[str | None] = mapped_column(String(2048), nullable=True)
    # LLM token usage + priced cost for this run. Null for reports generated
    # before cost tracking existed — cost can't be reconstructed after the fact.
    input_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    output_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    cost_usd: Mapped[float | None] = mapped_column(Float, nullable=True)
    # Soft delete: archived reports are hidden by default but can be restored.
    archived: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False, server_default="false"
    )
    # --- Credits ---------------------------------------------------------
    # Cost quoted at creation (stable for this report). Null for reports made
    # before credits existed — those generate without a charge.
    credit_cost: Mapped[int | None] = mapped_column(Integer, nullable=True)
    credit_state: Mapped[CreditState] = mapped_column(
        SAEnum(CreditState, name="reportcreditstate"),
        default=CreditState.none,
        nullable=False,
        server_default=CreditState.none.value,
    )
    # The open report_hold ledger entry, while credits are reserved.
    credit_hold_id: Mapped[uuid.UUID | None] = mapped_column(Uuid, nullable=True)
